### ISSUE TITLE
rotate actions token

### ISSUE THREAD

**Issue by hall** [boxboat/hobbyfarm-chart#160]
The [token used to publish the chart](https://github.com/hobbyfarm/hobbyfarm/blob/67fb7495ef1334816a17ac597d8b05d8b7f167f1/.github/workflows/publish-chart.yaml#L38) was created with GH's outdated format. I don't have permissions to update it but, even if I did, it should probably be managed by someone closer to the project.

**Comment by ibrokethecloud** [comment]
thanks @hall i will fix it up this week.

**Comment by jggoebel** [comment]
any updates on this? @ibrokethecloud

**Comment by jggoebel** [comment]
Token rotated by @ebauman
