### ISSUE TITLE
Overhaul step editing page

### ISSUE THREAD

**Issue by ebauman** [boxboat/hobbyfarm-chart#165]
Currently the step editing page is... busy:
![Screen Shot 2021-11-23 at 12 32 42 PM](https://user-images.githubusercontent.com/5565738/143083691-e7936b26-9509-4930-a275-580127487407.png)

There's almost more screen real estate devoted to how to edit the step than to the WYSIWYG editor. 

Let's see if we can move this into its own page? Or take all this content out of the product and move it to a product documentation page? Or heck even just a new tab popup that is still served by the product but doesn't clutter this page.

**Comment by jggoebel** [comment]
Working on this right now.
https://github.com/hobbyfarm/admin-ui/pull/148/files
![wip_editor](https://user-images.githubusercontent.com/86782124/217284665-defa672b-64b4-4845-9b5f-eacc61b048a5.PNG)
