### ISSUE TITLE
Integrate code-server

### ISSUE THREAD

**Issue by TimS-sva** [boxboat/hobbyfarm-chart#168]
**What would you like to be added**:
Intregrate code-server in the UI for comfortability.
https://github.com/cdr/code-server
**Why is this needed**:
Integrate code servers in the UI for convenience. Using code servers in courses and displaying code-server Window next to the VM window would allow students to edit files more easily.

**Comment by ebartz** [comment]
I think this could be nice in combination with this feature: https://github.com/hobbyfarm/hobbyfarm/issues/155

In that case one would deploy a pod containing codeserver instead of using a full vm.

**Comment by jggoebel** [comment]
for virtualmachines this is now implemented
