### ISSUE TITLE
[Bug] CRD versions are removed

### ISSUE THREAD

**Issue by ebauman** [boxboat/hobbyfarm-chart#176]
The apiextensions.k8s.io/v1beta1 API version of CustomResourceDefinition is no longer served as of v1.22.
(https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122)

We need to update the following projects:
h/gargantua
h/ec2-operator
h/droplet-operator
h/metal-operator

**Comment by ebauman** [comment]
@ibrokethecloud Can you take the operators and I'll fix garg?

**Comment by ibrokethecloud** [comment]
Changes for ec2-operator: https://github.com/hobbyfarm/ec2-operator/pull/10

Changes for droplet-operator:  https://github.com/hobbyfarm/droplet-operator/pull/1

**Comment by jggoebel** [comment]
We would also need the CRDs in the chart repository to be updated. I will create a PR for that.

**Comment by krumware** [comment]
(just adding detail)

Error: INSTALLATION FAILED: failed to install CRD crds/accesscode.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

This is the error message that will be seen if the k cluster is 1.22 or later, when deploying via helm chart

**Comment by jggoebel** [comment]
https://github.com/hobbyfarm/gargantua/pull/100 introduced typed CRDs of v1 to gargantua. Is this issue resolved?

**Comment by jggoebel** [comment]
Hobbyfarm now uses v1.
