### ISSUE TITLE
[Admin-UI] Display Creator of ScheduledEvent

### ISSUE THREAD

**Issue by jggoebel** [boxboat/hobbyfarm-chart#177]
**What would you like to be added**:
Currently scheduledevents can only be updated by the creator of the event. But who is the creator?
In the current version there is no way to see the creator of an SE in the UI.

**Why is this needed**:
To keep track of who created an SE.

**Comment by Cristoforo86** [comment]
pls assign me.

**Comment by jggoebel** [comment]
Resolved by https://github.com/hobbyfarm/admin-ui/pull/126
