### ISSUE TITLE
[Admin-UI] Display Error Message when you are not the creator

### ISSUE THREAD

**Issue by jggoebel** [boxboat/hobbyfarm-chart#179]
**What would you like to be added**:
Only the creator of an SE can edit the event. However the error is silent an is only displayed in the answer of the request.
We should look for 403 status (forbidden) on the result

**Comment by aminekortas** [comment]
i want fix this ticket

**Comment by jggoebel** [comment]
This issue is obsolete with the new RBAC implementation. Anyone with the scheduledevents.UPDATE right can update scheduled events.
