### ISSUE TITLE
Click-to-run disappears when code contains special characters

### ISSUE THREAD

**Issue by jwhb** [boxboat/hobbyfarm-chart#183]
**What happened**:
In student view in a session, click-to-run fields are sometimes missing. Sometimes fragments of the code are still displayed as plain text.

**What you expected to happen**:
Click-to-run fields always show completely.

**How to reproduce it (as minimally and precisely as possible)**:
I was able to reproduce the issue by:
* using double quotes in the ctr script
* using vm info variable in ctr script.

Scripts:
```
    ```ctr:rancher01
    echo "Hello World"
    ```
```
```
    ```ctr:rancher01
    echo ${vminfo:rancher01:private_ip}
    ```
```

**Anything else we need to know?**:


**Environment**:
- Gargantua version:
- UI/Admin version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by jggoebel** [comment]
As pointed out by you this is propably due to https://github.com/hobbyfarm/ui/blob/1c8d1358f401ac9cddf9bb69770fd5437baee9d5/src/app/hf-markdown/hf-markdown.component.ts#L55

**Comment by raphinesse** [comment]
`vminfo` code blocks are affected as well:

    ```vminfo:node01:vm_claim_id
    echo "${val}"
    ```
