### ISSUE TITLE
Verification checks against VM (Tasks for the user)

### ISSUE THREAD

**Issue by jggoebel** [boxboat/hobbyfarm-chart#193]
**What would you like to be added**:
The ability to verifiy different things on VMs.

For example if the user has the task to install a nginx pod with 3 replicas we could create 2 calls against the VM to check if the deployment exists and in a second check if the deployment has the desired replicas.

The most simple way would be to set the node, a name, a command and an expected result.
So for example:
node: node1
name: Deployment "admin-ui" in namespace "hobbyfarm" exists
command: `kubectl get deployments admin-ui -n hobbyfarm | grep -o "admin-ui"`
expected: `admin-ui`
would test if the admin-ui deployment exists in the hobbyfarm namespace on node1.

We could also display the progress based on the resolved tasks:

Example how this could look like
![](https://user-images.githubusercontent.com/44678880/162805515-2d4c70c8-a413-4631-ab59-3832a3faf93e.PNG)

The user should see which of the tasks are fulfilled and which are not. He should be able to click a button to test the current satisfaction of the tasks (But this should also be done periodically in the background)

**Why is this needed**:
The user wants to know if he has done all the things in the correct way. A tutor takes a long time to check if anybody got it right. Also the tutor would not be needed and users could take scenarios when there is no tutor available.

**Comment by byteloop** [comment]
GitHub has a display like this in the issues
![like_this](https://user-images.githubusercontent.com/44678880/162805515-2d4c70c8-a413-4631-ab59-3832a3faf93e.PNG)

**Comment by jggoebel** [comment]
https://pkg.go.dev/golang.org/x/crypto/ssh#Session.Output

**Comment by jggoebel** [comment]
Implemented in https://github.com/hobbyfarm/gargantua/pull/180
