### ISSUE TITLE
Can not start scenarios / AWS EC2 won't deploy 

### ISSUE THREAD

**Issue by lucathecreator** [boxboat/hobbyfarm-chart#195]
**What happened**:

Started the scenario, the vm stucks in provisioning status.

There a no logs in any containers that point to an error. 

The pods don't send traffic to AWS to deploy the EC2 machines.

- Gargantua version: 1.0.0
- UI/Admin version: 1.0.0

**Comment by lucathecreator** [comment]
I installed the EC2 Operator and the hf-shim-operator additionally. 
Also i added the crds of of the droplet-operator. 

There is still no outgoing traffic when i start a scenario as a user and also nothing in the EC2 logs.

**Comment by jggoebel** [comment]
Are you using the release 1.0.0 or a build of the current master version?

**Comment by lucathecreator** [comment]
I used the 1.0.0 version and manually installed the EC2-operator and the hf-shim-operator since they were not included in the helm chart.

**Comment by lucathecreator** [comment]
Any Ideas what I could check?

**Comment by jggoebel** [comment]
Do you have any logs from gargantua?
Otherwise i could offer a call to check on your cluster.

**Comment by lucathecreator** [comment]
The Gargantua logs are pretty empty. 

If it is possible for you a call would be highly appreciated! 

How can we set it up?

**Comment by jggoebel** [comment]
> The Gargantua logs are pretty empty.

But VM CRDs are created right? So the controllers are running?
The version 1.0.0 may have a problem starting the controllers.

Please check this first

**Comment by lucathecreator** [comment]
The Virtualmachineclaim is created but no ec2 instances are created in AWS 

```
k get virtualmachineclaims.hobbyfarm.io -n hobbyfarm
NAME                 AGE
dynamic-wfqcipczj5   7m3s
```

**Comment by jggoebel** [comment]
could you also do a describe on the vmc?

**Comment by jggoebel** [comment]
or even better:

`kubectl get vmc dynamic-wfqcipczj5 -o yaml`

**Comment by lucathecreator** [comment]
yes of course: 

`apiVersion: hobbyfarm.io/v1
kind: VirtualMachineClaim
metadata:
  creationTimestamp: "2022-04-20T15:18:30Z"
  generation: 2
  labels:
    accesscode.hobbyfarm.io: rodeo
    hobbyfarm.io/scheduledevent: se-6fbbp7rcqh
    hobbyfarm.io/session: ss-vi7vhaj7st
    hobbyfarm.io/user: u-dsptno3vbw
    virtualmachinetemplate.hobbyfarm.io/ubuntu2004: "true"
  name: dynamic-wfqcipczj5
  namespace: hobbyfarm
  resourceVersion: "43429964"
  uid: fc2c36c6-5411-4054-8efe-42d98cf0d8b3
spec:
  base_name: dynamic-wfqcipczj5
  dynamic_bind_capable: true
  id: dynamic-wfqcipczj5
  restricted_bind: true
  restricted_bind_value: se-6fbbp7rcqh
  user: u-dsptno3vbw
  vm:
    Cluster01:
      template: ubuntu2004
      vm_id: dynamic-wfqcipczj5-cb8de6d5
    Rancher01:
      template: ubuntu2004
      vm_id: dynamic-wfqcipczj5-3d9ccdf3
status:
  bind_mode: dynamic
  bound: true
  dynamic_bind_request_id: ""
  ready: false
  static_bind_attempts: 0
  tainted: false`

**Comment by jggoebel** [comment]
And could you also provide yaml for the VMT for ubuntu2004 and the environment. 

I will check if everything is configured correctly.

**Comment by lucathecreator** [comment]
This is the Yaml of the VMT

`~ ❯ k get virtualmachinetemplates -n hobbyfarm  -o yaml
apiVersion: v1
items:
- apiVersion: hobbyfarm.io/v1
  kind: VirtualMachineTemplate
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"hobbyfarm.io/v1","kind":"VirtualMachineTemplate","metadata":{"annotations":{},"name":"ubuntu2004","namespace":"hobbyfarm"},"spec":{"id":"ubuntu2004","image":"ami-05f7491af5eef733a","name":"ubuntu2004","resources":{"cpu":2,"memory":4096,"storage":24}}}
    creationTimestamp: "2022-04-25T07:28:59Z"
    generation: 2
    name: ubuntu2004
    namespace: hobbyfarm
    resourceVersion: "46025723"
    uid: a76f0a33-5fa5-4442-974e-40314b436116
  spec:
    id: ubuntu2004
    image: ami-05f7491af5eef733a
    name: ubuntu2004
    resources:
      cpu: 2
      memory: 4096
      storage: 24
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""`

**Comment by jggoebel** [comment]
> image: ami-05f7491af5eef733a

okey you have set the image here, but have you also added it to the environment?
Currently the image provided in the VMT Spec is ignored, see https://github.com/hobbyfarm/hobbyfarm/issues/197

You would have to provide it to the template mapping in the environment.

**Comment by lucathecreator** [comment]
Yes the image is also mapped in the environment. 
Here is that part of the yaml: 

    template_mapping:
      ubuntu2004:
        image: ami-05f7491af5eef733a
        instanceType: c4.xlarge
        rootDiskSize: "50"

**Comment by jggoebel** [comment]
Okey and you said that a vmclaim CRD was created, but a type VM CRD is not created, right?

**Comment by jggoebel** [comment]
Could you also provide the 
capacity parts of the environment?
So count capacity or raw capactiy depending on which you have set in the environment

**Comment by lucathecreator** [comment]
Sure. I haven't set any yet. This worked with the older hobbyfarm version. Do they need to be set now? 

`spec:
    burst_capable: true
    burst_capacity:
      cpu: 0
      memory: 0
      storage: 0
    burst_count_capacity: null
    capacity:
      cpu: 0
      memory: 0
      storage: 0
    capacity_mode: count
    count_capacity: null`

**Comment by jggoebel** [comment]
as far as i know the count_capacity and burst_count capacity need to be set when using capacity_mode count. The value is ignored but the mapping to the template has to be set.

```yaml
spec:
  burst_capable: true
  capacity_mode: count
  burst_count_capacity:
    ubuntu2004: 1000
  count_capacity:
    ubuntu2004: 1000
```

But i think this is the same as before, the mapping was always needed when using count mode & dynamic provisioning mode

**Comment by lucathecreator** [comment]
I changed the values, but the ec2 instances still won't come up: 

spec:
  burst_capable: true
  burst_capacity:
    cpu: 0
    memory: 0
    storage: 0
  burst_count_capacity:
    ubuntu2004: 1000
  capacity:
    cpu: 0
    memory: 0
    storage: 0
  capacity_mode: count
  count_capacity:
    ubuntu2004: 1000

**Comment by nnoethling** [comment]
Also ran into this issue, please help

**Comment by lucathecreator** [comment]
In Environment configuration module was missing, also used newer image for the terraform executor. 

``` 
  environment_specifics:
    executor_image: lwaas/terraform-executor:v1
    module: tf-module 

```
