### ISSUE TITLE
Add the ability to switch between ScheduledEvents

### ISSUE THREAD

**Issue by ebauman** [boxboat/hobbyfarm-chart#227]
Along with the course or scenario we should display the access code that is providing that scenario. 
This will allow users to choose which course or scenario they should use based on the access code.

The scenario may be the same but the scheduled event in the future may include additional data such as files for download, etc.

**Comment by jggoebel** [comment]
-> Context Switching Between ScheduledEvents to make 100% sure in which context the scenario gets executed.
-> Remove Menu Bar ("Home")
-> Add context switch with ScheduleDEvent Names there

-> Gargantua will deliver a map with accesscode->scheduledEventName for all valid events for a user
-> Gargantua Route for teching Scenarios / Courses based on single accesscode

-> Display progressbar to the user (5 out of 7 scenarios completed (Or more like 20 out of 30 steps.)

**Comment by jggoebel** [comment]
under "manage accesscodes" we can also display invalid codes

**Comment by jggoebel** [comment]
Release in the 2.0.6
