### ISSUE TITLE
Consider removing burst components of Environments

### ISSUE THREAD

**Issue by ebauman** [boxboat/hobbyfarm-chart#236]
Currently the environment resource defines two burst-related configuration items, `burst_capable` and `burst_count_capacity`. These fields existed from the beginning of HobbyFarm when it was initially decided to differentiate between ahead-of-time (AOT) and on-demand (dynamic) provisioning. 

More recent provisioning strategies have resulted in these fields being largely redundant. Typical HobbyFarm users do not need to distinguish whether or not an environment is burst capable - the provisioner can provide either option and the user needs to only specify the overall capacity of the environment.

I recommend we remove these fields in favor of a general approach involving only count capacity considerations independent of provisioning strategy.

**Comment by jggoebel** [comment]
I support this!
