### ISSUE TITLE
Can we eliminate resource-based capacity tracking?

### ISSUE THREAD

**Issue by ebauman** [boxboat/hobbyfarm-chart#237]
Currently HobbyFarm is capable of tracking utilization in an environment based not only on the count of virtual machines deployed, but also theoretically the amount of CPU, memory and disk storage being taken up by the VMs. 

In practice, this has almost never been done. Most users are in cloud providers and are concerned with node counts not resource consumption. Further, the abstract nature of the vm template (where the resource amounts are specified) doesn't directly translate to what consumption would be in a particular environment. Additionally, this mechanism may not even work at ll (I did say it only _theoretically_ works ;) )

I propose we remove the concept of tracking VMs by resource consumption and focus solely on the count of VMs in an environment. It is then left as an exercise to the user to determine what capacity their environment has for different types of virtual machines.

**Comment by jggoebel** [comment]
Supporting this too. Calculating based on capacity makes the provisioning even more complex. 
Removing this should not be very hard but would require environment/v2

We could in the same step fix https://github.com/hobbyfarm/hobbyfarm/issues/234

**Comment by jggoebel** [comment]
also in the same step fix #236 so we do not need to release two versions
