### ISSUE TITLE
Status subresources do not get appropriately updated

### ISSUE THREAD

**Issue by ebauman** [boxboat/hobbyfarm-chart#247]
**What happened**: Upon ScheduledEvent creation, the new SE does not immediately become active. In fact, the `status` subresource of the CR does not get created. 

**What you expected to happen**: I expect an SE to immediately become active (`status.active`) post-creation. 

**How to reproduce it (as minimally and precisely as possible)**: Install HobbyFarm into a clean cluster, using v2.0.5 or under.

**Anything else we need to know?**: I believe this is related to logic in HobbyFarm resource creation specifically not calling `UpdateStatus()` during resource creation.
If `UpdateStatus()` is not called, per k8s docs this does not result in the `status` subresource being created, which matches the behavior I am seeing. 

**Environment**:
- Gargantua version: v2.0.1
- UI/Admin version: v2.0.x
- Kubernetes version (use `kubectl version`): v1.22+
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by jggoebel** [comment]
When is a scheduledEvent status.active even false? It can only be done manually right?

scheduledevent.go:274 currently sets the scheduledEvent status.Active to true upon creation, i wonder why this might not be set.

**Comment by jggoebel** [comment]
In fact for no ressource UpdateStatus has ever been called. Only normal updates are done

**Comment by ebauman** [comment]
This worked in the past because we never defined the CRD as having a Status subresource. 
Now that it does (we always should have) we need to make adjustments.

In fact, this applies to all CRs with a status subresource.

**Comment by hornet83** [comment]
Hi,
does this relate to scheduledevents staying inactive?
![image](https://user-images.githubusercontent.com/31092498/202401924-349593cd-fff8-4853-bca2-baeb95fb7f0a.png)

Is there a way to change the status manually?

The only log we could fine is this - not sure if it is related though:
```
I1117 09:07:39.816252       1 accesscode.go:58] access code example seems to be invalid
E1117 09:07:39.816274       1 scenarioserver.go:291] error retrieving access code: example insane result found
I1117 09:07:39.816858       1 accesscode.go:58] access code example seems to be invalid
E1117 09:07:39.816987       1 courseserver.go:451] error retrieving course ids for access code: example error finding access code example: insane result found
I1117 09:07:40.962514       1 authclient.go:95] validated user user@domain.de!
```


Thanks,
Stefan

**Comment by jggoebel** [comment]
Hey Stefan,
regarding the error log:
This only says that a user has the access code "example" which does not relate to any active event. Thus this is only resulting from the original problem of the event being inactive.

Which Kubernetes distro are you using?

**Comment by hornet83** [comment]
Hey, thanks for the quick reply!
we tested with 1.21.14 and 1.23.12 (both rke) - same result with either

**Comment by jggoebel** [comment]
We will further investigate this issue. We are running k3s and it seems there is a difference on how theese both handle the status subressource.

For now you can try to set the event to active manually by editing the event via kubernetes directly.

**Comment by hornet83** [comment]
thanks, we will give k3s a go - are you able to give me an example yaml for an active status? we tried the following, which didn't work:

```
apiVersion: hobbyfarm.io/v1
kind: ScheduledEvent
metadata:
  annotations:
    meta.helm.sh/release-name: hf
    meta.helm.sh/release-namespace: hobbyfarm
  creationTimestamp: "2022-11-16T14:59:06Z"
  generation: 5
  labels:
    app.kubernetes.io/managed-by: Helm
  name: example-event
  namespace: hobbyfarm
  resourceVersion: "337820"
  uid: 260893bd-4ccb-44e7-8cb9-9d2cf53b1dcf
spec:
  access_code: example
  courses: []
  creator: ""
  description: test1
  end_time: Thu Nov 24 08:58:18 UTC 2022
  event_name: test1
  on_demand: true
  printable: false
  required_vms:
    example-environment:
      ubuntu1604-docker1: 10
  restricted_bind: true
  restricted_bind_value: example-event
  scenarios:
  - example-scenario
  start_time: Thu Nov 17 08:58:18 UTC 2022
status:
  active: true
```

**Comment by jggoebel** [comment]
Try by adding the normal status fields

```
status:
  access_code_id: ""
  active: true
  finished: false
  provisioned: false
  ready: false
  vmsets: []
  ```

**Comment by hornet83** [comment]
thanks for the tip - but doesnt work, tried this config and no luck

```
apiVersion: hobbyfarm.io/v1
kind: ScheduledEvent
metadata:
  creationTimestamp: "2022-11-16T16:12:27Z"
  generation: 5
  name: se-se-dgysn3yg5l
  namespace: hobbyfarm
  resourceVersion: "54345479"
  uid: e631df20-17b7-4ecc-a697-125dc91b3d36
spec:
  access_code: ansible01
  courses: []
  creator: u-myx6cp6bk7
  description: test
  end_time: Wed Nov 23 16:09:57 UTC 2022
  event_name: test
  on_demand: false
  printable: false
  required_vms:
    aws-eu-central-1:
      ubuntu2004: 12
  restricted_bind: true
  restricted_bind_value: se-se-dgysn3yg5l
  scenarios:
  - ansible-training
  start_time: Wed Nov 16 16:09:55 UTC 2022
status:
  access_code_id: ""
  active: true
  finished: false
  provisioned: false
  ready: false
  vmsets: []
```

**Comment by jggoebel** [comment]
Okey thanks for testing this. I guess we have some work todo here regarding RKE

**Comment by hornet83** [comment]
we did setup the k3s cluster as well and are having exactly the same issue.. we also tried changing the status manually with no success, so this issue seems to be unrelated to the kubernetes distro, any ideas?

**Comment by jggoebel** [comment]
Yes as it seamed using status as a subresource always resulted in this issues. 
I finally implemented calling UpdateStatus() in gargantua.
Also fixed some other smaller issues with it.

**Comment by hornet83** [comment]
Thanks, we will give it a test and report back :)

**Comment by jggoebel** [comment]
Okey please respond ASAP if you got the version up running. I will then create a new chart release
