### ISSUE TITLE
CRDs are missing in Helm Chart 

### ISSUE THREAD

**Issue by lucathecreator** [boxboat/hobbyfarm-chart#249]
**What happened**:
Tried to install Hobbyfam into a new cluster

**What you expected to happen**:
Successful installation

**How to reproduce it (as minimally and precisely as possible)**:
Install Hobbyfarm in a new cluster without any of the hobbyfarm crds 

**Anything else we need to know?**:
Got following error: 

```
helm install hf hobbyfarm/hobbyfarm -n hobbyfarm -f values.yaml --create-namespace
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "DynamicBindConfiguration" in version "hobbyfarm.io/v1", unable to recognize "": no matches for kind "Environment" in version "hobbyfarm.io/v1", unable to recognize "": no matches for kind "Scenario" in version "hobbyfarm.io/v1", unable to recognize "": no matches for kind "ScheduledEvent" in version "hobbyfarm.io/v1", unable to recognize "": no matches for kind "VirtualMachineTemplate" in version "hobbyfarm.io/v1"]
```

Installed following crds which I exported from an old installation: 
```

dynamicbindconfigurations.hobbyfarm.io.yaml
environments.hobbyfarm.io.yaml
modules.terraformcontroller_crd.yaml
scenarios.hobbyfarm.io.yaml
scheduledevents.hobbyfarm.io.yaml
virtualmachinetemplates.hobbyfarm.io.yaml
```
Also couldn't find the CRD files to install them manually in git repo.

**Comment by jggoebel** [comment]
Which values are you using?

We removed the CRDs from the chart repo. Gargantua will install them when starting and keeps them in the newest state which is working for this gargantua version.

**Comment by jggoebel** [comment]
Have you enabled seed? Disable it please in the values. We should remove the seed values from the chart repository.

**Comment by lucathecreator** [comment]
Hi, 

thanks for the quick reply. 
I use the current version of the values.yaml. 

I deactivated the seed option in the values.yaml, then it worked fine! 

I always used the seed, so I have a reference for the CRDs.
