### ISSUE TITLE
Filtering scenarios on scheduled event creation

### ISSUE THREAD

**Issue by jggoebel** [boxboat/hobbyfarm-chart#260]
Same as https://github.com/hobbyfarm/hobbyfarm/issues/232 but for scheduled event creation

**Comment by PhilipAB** [comment]
Assigned to @abrahimi93

Acceptance criteria:
 - [ ] Create a scenario-filter.component to reuse the code instead of duplicating it

**Comment by jggoebel** [comment]
implemented in https://github.com/hobbyfarm/admin-ui/pull/145
