### ISSUE TITLE
"module name does not exist or is empty in vm config for vmt vmt-x"

### ISSUE THREAD

**Issue by krumware** [boxboat/hobbyfarm-chart#261]
**What happened**: Attempted run a scenario with a newly setup environment and VMT

**What you expected to happen**: The ec2 instances should allocate

**How to reproduce it (as minimally and precisely as possible)**: Fresh install, attempt to run a rodeo scenario with a new environment and VMT

**Anything else we need to know?**: Gargantua is reporting `tfpcontroller.go:156] module name does not exist or is empty in vm config for vmt vmt-xx` when a user attempts to start a scenario. Everything **appears** to be configured correctly. Looking at the code, it appears that there may need to be a field in the VMT resource for module? Not certain. Checked the docs and can't figure out what's missing https://hobbyfarm.github.io/docs/architecture/resources/virtualmachinetemplate/

**Environment**:
- Gargantua version: 2.0.3
- UI/Admin version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: AWS via terraform config in helm
- OS (e.g: `cat /etc/os-release`):

**Comment by jggoebel** [comment]
We fixed this together. This was a configuration issue.

**Comment by lucathecreator** [comment]
Can you explain, where the error in the configuration was? Im running into the same error. 

Thanks!

**Comment by jggoebel** [comment]
If i remember correctly the issue was that the wrong environment (where no "module" was defined.) was selected during ScheduledEvent creation 
@lucathecreator do you provide a module in the environment?
the key has to be `module`. It has to be provided on either the environment, the vmt or the environment specifics for vmts.

**Comment by jggoebel** [comment]
See the code where this gets logged:

```
moduleName, exists := config["module"]
			if !exists ||  moduleName == "" {
				return fmt.Errorf("module name does not exist or is empty in vm config for vmt %s", vmt.Name), true
			}
```

Where `config` is calculated based on this list, getting more specific with each step
1. VMT
2. Environment
3. Environment VMT configuration (Env specifics)

So if module is defined in 2 and 3, the one in 3 is used.

**Comment by lucathecreator** [comment]
Thanks! 

Yes i provided the module in the environment now: 

``` 
environment_specifics:
  module: tf-module
  executor_image: oats87/terraform-controller-executor:hfv1
```

but i get following error: 

```

 Error installing provider "aws": openpgp: signature made by unknown entity.                                                                     │
│                                                                                                                                                 │
│ Terraform analyses the configuration and state and automatically downloads                                                                      │
│ plugins for the providers used. However, when attempting to download this                                                                       │
│ plugin an unexpected error occured.                                                                                                             │
│                                                                                                                                                 │
│ This may be caused if for some reason Terraform is unable to reach the                                                                          │
│ plugin repository. The repository may be unreachable if access is blocked                                                                       │
│ by a firewall.                                                                                                                                  │
│                                                                                                                                                 │
│ If automatic installation is not possible or desirable in your environment,                                                                     │
│ you may alternatively manually install plugins by downloading a suitable                                                                        │
│ distribution package and placing the plugin's executable file in the                                                                            │
│ following directory:                                                                                                                            │
│     terraform.d/plugins/linux_amd64                                                                                                             │
│                                                                                                                                                 │
│ : exit status 1                                                                                                                                 │
│ Stream closed EOF for hobbyfarm/job-dynamic-x (agent)

```

I got the image name from the seed data, do i have to use another image?

**Comment by jggoebel** [comment]
is the tf module outdated? Last updated 3 years ago
https://github.com/hobbyfarm/tf-module-aws

I have not used the aws module yet.
