### ISSUE TITLE
Problems with the installation

### ISSUE THREAD

**Issue by antton** [boxboat/hobbyfarm-chart#294]
Dear,

I am writing to seek your assistance with the installation of HobbyFarm. I have carefully followed the documentation instructions provided, but unfortunately, I have encountered some difficulties that have prevented me from completing the installation process.

I have made several attempts to troubleshoot the issue by re-reading the instructions and researching possible solutions online. However, I have not been able to resolve the issue on my own.

Would it be possible for you to provide some guidance on how I could overcome this obstacle? I would be grateful for any assistance you could offer.

I'm trying to make the installation in an AWS EC2 VM starting from this repository. I have noticed, docker-compose.yml rancher k3s version is not "compatible" with the actual hobbyfarm version. I believe that this discrepancy may be causing other users to encounter similar problems, and it would be beneficial to address this issue promptly.

Thank you for your time and consideration. I look forward to hearing from you soon.

**Comment by jggoebel** [comment]
Hello!

Have you any error messages during installation?
The docker-compose is outdated. Pleaes deploy hobbyfarm via the helm chart on a existing kubernetes cluster.

**Comment by antton** [comment]
Ok, 

I will start the whole process over again.

Thanks for your attention
