### ISSUE TITLE
Cannot add access code, "bad parameters passed"

### ISSUE THREAD

**Issue by ebauman** [boxboat/hobbyfarm-chart#304]
**What happened**: Attempted to add access code "etest2" to user, received UI error "error adding access code".
Gargantua logs:
```
E0328 17:12:49.566195 1 authserver.go:270] bad parameters passed, :etest2
```

**What you expected to happen**: No error

**How to reproduce it (as minimally and precisely as possible)**: Try to add an access code 

**Anything else we need to know?**:

**Environment**:
- Gargantua version: v2.0.3
- UI/Admin version: v2.0.1 
- Kubernetes version (use `kubectl version`): v1.24.10
- Cloud provider or hardware configuration: RKE2
- OS (e.g: `cat /etc/os-release`):

**Comment by jggoebel** [comment]
Seems like the user id is not set: See `authserver:305`. 
But weirdly AddAccessCodeFunc should have failed on that when executing AuthN

**Comment by jggoebel** [comment]
Oh. Had you installed a later version of hobbyfarm?
This commit https://github.com/svalabs/gargantua/commit/a57c2fa7f8e62a07fa8dd36f3846ee0405fd8775#diff-8646268a3711bdfe9b88adbbafd8ca4f1703ead28977b3e5bd9af0a8d51d4b16 or after this commit?

The `.spec.id` field was removed and replaced by using the `.metadata.name` field

**Comment by jggoebel** [comment]
So maybe we should release a new gargantua + ui + admin-ui version. 
So much has changed since december

**Comment by ebauman** [comment]
We absolutely need to. The product is broken at this point if we are relying on unreleased UI versions.

**Comment by jggoebel** [comment]
Yes we should release a new 2.x version.

**Comment by jggoebel** [comment]
We released a new version that fixed this issue of two incompatible versions
