### ISSUE TITLE
No cleanup of Progress resources

### ISSUE THREAD

**Issue by ebauman** [boxboat/hobbyfarm-chart#307]
Currently, Progress resources are never cleaned up. There is no call to their typed clientset Delete() anywhere in Gargantua code. 
We should clean these up, probably with some kind of garbage collection timeout. Or a finalizer ? but those suck

**Comment by jggoebel** [comment]
Progressed are deleted when the corresponding scheduled event ist deleted. 

The event holds ownership over the progresses. Therefore kubernetes deleted the progresses automatically upon deletion of the se

**Comment by ebauman** [comment]
But scheduled events aren't deleted unless we go through and prune them, correct?

**Comment by jggoebel** [comment]
Correct. This ensures you can view the statistics of ScheduledEvents until we have a way of storing progress outside the etcd.

**Comment by jggoebel** [comment]
With the implemented retention time we can define how long SEs should be stored after the event finished. This will also clean up the progress resources associated with this event.
