### ISSUE TITLE
admin-ui does not display the correct version in "about" box

### ISSUE THREAD

**Issue by hguermeur** [boxboat/hobbyfarm-chart#319]
**What happened**:
admin-ui does not display the correct version in "about" box
![image](https://github.com/hobbyfarm/hobbyfarm/assets/116629601/4671abd0-1382-421a-9da8-2afc102cb34f)

**What you expected to happen**:
ui and admin-ui should display the release version in "about" box.

**How to reproduce it (as minimally and precisely as possible)**:
Open admin-ui, click user personal menu, about : bad version.
Open ui, click user personal menu, about : no version.

**Anything else we need to know?**:
[UI should display its version somewhere #59](https://github.com/hobbyfarm/hobbyfarm/issues/59)

**Environment**:
- Gargantua version: **3.0.0**
- UI/Admin version: **3.0.0** (but it was an old bug :-) )
- Kubernetes version (use `kubectl version`): v1.24.13+rke2r1
- Cloud provider or hardware configuration: AWS

**Comment by jggoebel** [comment]
We removed the ability to view the current version in the about box a while ago.
It is possible to view the installed version directly in the kubernetes cluster or in the values.yml.
