### ISSUE TITLE
Misaligned Terminal Window Size

### ISSUE THREAD

**Issue by zackbradys** [boxboat/hobbyfarm-chart#359]
**What happened**: In the HobbyFarm UI, the terminal window size is always misaligned, different size on each reload page, or various other size and spacing issues.

**What you expected to happen**: All terminal windows sizes to be consistence and completely fill the screen.

**How to reproduce it (as minimally and precisely as possible)**: Open the HobbyFarm UI, with multiple virtual machines, and click through the virtual machine tabs.

<img width="1185" alt="hobbyfarm-screenshot-one" src="https://github.com/hobbyfarm/hobbyfarm/assets/7769650/bac943dc-4bb5-4484-8dd4-f5b050be643d">

<img width="1185" alt="hobbyfarm-screenshot-two" src="https://github.com/hobbyfarm/hobbyfarm/assets/7769650/de947a69-f1e5-4dbc-b9cf-a1c78746e271">

<img width="1185" alt="hobbyfarm-screenshot-three" src="https://github.com/hobbyfarm/hobbyfarm/assets/7769650/fa4a6f27-bcc7-4e17-8656-312e2268f6cd">

**Environment**:
- Gargantua version: `hobbyfarm/gargantua:v3.0.0`
- UI/Admin version: `hobbyfarm/ui:master` and `hobbyfarm/admin-ui:master`
- Kubernetes version (use `kubectl version`): `v1.25.14+rke2r1`
- Cloud provider or hardware configuration: `AWS`
- OS (e.g: `cat /etc/os-release`): 
```
NAME="SLES"
VERSION="15-SP5"
VERSION_ID="15.5"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp5"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

**Comment by jggoebel** [comment]
Which browser are you using?

**Comment by zackbradys** [comment]
It varies... I mainly use Safari and Chrome, but I think @clemenko had it happen on Firefox as well.

**Comment by zackbradys** [comment]
Hey @jggoebel and @ebauman, had this happen during another session. Any updates here?

**Comment by jggoebel** [comment]
That is weird. I could not reproduce this myself but i had a coworker running into the same issue.

**Comment by clemenko** [comment]
I had to refresh to even get the websockets to connect. 
![Kapture 2023-11-22 at 10 59 58](https://github.com/hobbyfarm/hobbyfarm/assets/3177276/6180f003-0142-4284-9e2b-a22978847f65)

**Comment by jggoebel** [comment]
@clemenko  this could be happening if the SSH Daemon takes some time to come up on freshly created VMs

**Comment by clemenko** [comment]
it was a bad AMI.
