### ISSUE TITLE
User Logout After A Period of Time has Passed

### ISSUE THREAD

**Issue by eengelking** [boxboat/hobbyfarm-chart#362]
**What would you like to be added**:
Users should be logged out of their current session after a set period of time has passed, and re-directed to the login page. This can be set in the admin interface or as part of the deployment via Helm in the UI section.

**Why is this needed**:
* Admin UI security.
* User UI security.
* The UI is still accessible if changes occur in the backend.
* White screen issues occur due to backend changes.

**Comment by jggoebel** [comment]
This is currently done after 24 hours. 
we could make this configurable via the settings if this is needed?

**Comment by eengelking** [comment]
For a lot of the use-cases I personally have, 24 hours is far too long. It needs to be customizable. Ideally, in two places: the Helm values.yaml for initial configuration and in the admin interface post deployment.

**Comment by jggoebel** [comment]
Would it be okey if it only can be set in the admin ui settings? Otherwise it would be overridden by the helm chart when updating

**Comment by eengelking** [comment]
I'm didn't consider the impact of performing an update via Helm. That makes sense to only have it in admin.
