### ISSUE TITLE
About Modal Improvements

### ISSUE THREAD

**Issue by eengelking** [boxboat/hobbyfarm-chart#363]
**What would you like to be added**:
* The about modal doesn't currently wrap text.
* Only the UI version is shown. It would be useful to have: admin-ui, gargantua, gargantua-shell, ui, and any provisioner versions.

**Why is this needed**:
* The about modal just looks unfinished.
* The UI versions for all running applications is useful for troubleshooting. It would be a nice, centralized location to grab the required information for bug reporting.

**Comment by jggoebel** [comment]
When we touch the about modal we can rework the links to be configured by the settings instead of helm values

**Comment by jggoebel** [comment]
Buttons can be configured via settings.
Further adjusting the about modal is not planned right now as all information regarding version can be grabbed from the deployment or values.yml.
