### ISSUE TITLE
Scenario Category Dropdown does not refresh after creating or deleting categories

### ISSUE THREAD

**Issue by eengelking** [boxboat/hobbyfarm-chart#364]
**What happened**:
When creating a scenario, the page doesn't automatically refresh with the newly created scenario. You must manually refresh the page to see the scenario.

**What you expected to happen**:
After a scenario is created, the page should dynamically update to show the new scenario without having to manually refresh.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a scenario.
2) Refresh the page to see the scenario.

**Anything else we need to know?**:
This is also true for categories. When adding categories, they do not appear until the page has been refreshed.

**Environment**:
- Gargantua version: hobbyfarm/gargantua:v3.0.1-rc0
- UI/Admin version: hobbyfarm/admin-ui:v3.0.0, hobbyfarm/ui:v3.0.0
- Kubernetes version (use `kubectl version`): K3s v1.27.6+k3s1
- Cloud provider or hardware configuration:
```bash
6-core CPU
64GB RAM
50GB Disk
```
- OS (e.g: `cat /etc/os-release`):
```bash
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by jggoebel** [comment]
I will have to check again but I think I fixed this for scenarios in https://github.com/hobbyfarm/admin-ui/pull/184.

by categories you mean the category filter drop-down on the scenario list page?

**Comment by eengelking** [comment]
Correct. After I've created a category, the drop down menu in the scenario page isn't dynamically updated.
