### ISSUE TITLE
Logs or Errors in UI Interfaces

### ISSUE THREAD

**Issue by eengelking** [boxboat/hobbyfarm-chart#366]
**What would you like to be added**:
It would be very useful to have a modal, status page, or log interface to show connectivity issues to one or more backend environments.

**Why is this needed**:
ATM, a user must go into the developer tools in the browser and review the console and/or network for errors. This is not very intuitive for non-developer users. Instead, if the UI cannot access the backend interface, there should be an easy means to determine if everything is working as expected.

**Comment by jggoebel** [comment]
by "backend-environments" you mean the shell proxy or gargantua?

**Comment by jggoebel** [comment]
would a /healthz page appropiate that tests a websocket connection to an endpoints?

so like /healthz/<env-name> will try to create a websocket to this environments shell endpoint. That way it could be tested without even be logged into hobbyfarm

**Comment by eengelking** [comment]
> would a /healthz page appropiate that tests a websocket connection to an endpoints?
> 
> 
> 
> so like /healthz/<env-name> will try to create a websocket to this environments shell endpoint. That way it could be tested without even be logged into hobbyfarm

Exactly. And a status page that just shows everything is up and responding as expected.

**Comment by jggoebel** [comment]
I am unsure if we can test if "everything" is up. We can surely test if one given shell endpoint is up and running. In the case the platform has hundres of environments configured it should not test connection against every endpoint. also i am unsure if we want to give the user a list of all shell endpoints if the user is not registered.

**Comment by eengelking** [comment]
> I am unsure if we can test if "everything" is up. We can surely test if one given shell endpoint is up and running. In the case the platform has hundres of environments configured it should not test connection against every endpoint. also i am unsure if we want to give the user a list of all shell endpoints if the user is not registered.

I apologize. I think I may have miscommunicated intent. By backend environments, I'm just meaning the services running to ensure they're operating as expected (ui, admin, gargantua, shell, etc). I did not intend for the virtual machines to be included.

**Comment by jggoebel** [comment]
Okey but then i do not see the point here.
What i thought is that we test the Shell Proxy as users might need to configure their firewall to use hobbyfarm and they oculd use the /healthz page to verify that they can use hobbyfarm.

To verify the backend environments is not needed for most of the users, and the admin could just look inside the cluster.
We would need to allow access to every backend service from the UI which is currently not needed. (AccessCode Service for example only provides cluster internal gRPC routes that can not be reached from the UI)

**Comment by jggoebel** [comment]
We added a health endpoint to the shell proxy:
https://github.com/hobbyfarm/gargantua/pull/195

The user can now open a specific testing page to verify he can open a websocket to the shell proxy.
