### ISSUE TITLE
Rename Websocket Endpoint to Shell Endpoint in Environment

### ISSUE THREAD

**Issue by eengelking** [boxboat/hobbyfarm-chart#368]
**What would you like to be added**:
In Environments via the Admin interface, rename `Websocket Endpoint` to `Shell Endpoint URL`.

**Why is this needed**:
From a development perspective, having the `Websocket Endpoint` named in such as way makes sense. However, for non-developer users this may lead to confusion. Instead, this should be renamed `Shell Endpoint URL` with an information button that explains its purpose and/or points to documentation which explains the purpose.

**Comment by jggoebel** [comment]
Good idea, will it be enough to rename this in the UI or should it be done for the CRD as well? We would have to issue a new version of environment for this

**Comment by eengelking** [comment]
Valid point. For consistency, it should probably be renamed everywhere.

**Comment by jggoebel** [comment]
Currently not planned
