### ISSUE TITLE
Provide an Option to Rename Scenarios

### ISSUE THREAD

**Issue by eengelking** [boxboat/hobbyfarm-chart#371]
**What would you like to be added**:
Ability to rename `Scenarios` to something else.

**Why is this needed**:
The term `Scenario` can be confusing. For example, when I deploy an environment, I would like to call them `Labs` instead.

**Comment by jggoebel** [comment]
We can not rename this for the whole plattform. Some users call it Scenario, some call it labs. For the purpose of backwards compatiblity we stick to the term Scenario.

Adjusting this on every place it occures (gargantua, CRDs etc.) is too much work for the purpose it solves
