### ISSUE TITLE
Admin Option to Start All VMs in a Scheduled Event

### ISSUE THREAD

**Issue by eengelking** [boxboat/hobbyfarm-chart#373]
**What would you like to be added**:
As an Admin, I would like the ability to start all of the VMs for my users at the same time.

**Why is this needed**:
Having all of the users up and running without waiting is very useful for events where every minute counts. I may not necessarily have a few extra minutes to wait for a VM to start up for each user, or troubleshoot when a VM doesn't come up successfully. Instead, as an admin, being able to bring up all VMs at once and verify they're all working saves time and energy.

**Comment by jggoebel** [comment]
This is the option „on demand“ on scheduled events.

turn it off to set it to static provisioning (VMs start right away at the start of the events beginning time

**Comment by eengelking** [comment]
OK, good to know. I'll update the documentation with this information.
