### ISSUE TITLE
Updating a scenario name does not propagate throughout the platform

### ISSUE THREAD

**Issue by eengelking** [boxboat/hobbyfarm-chart#378]
**What happened**:
A scenario was created and given the name "Foo".  Later, this scenario was renamed "Bar".  In the `Scenario Details` portion of the scenario, the name is updated as expected. However, in the list of available Scenarios, the name does not update. When going to a Course and selecting a Scenario, the old data is shown.

When reviewing the associated Scenario manifest, I can see it is being updated as expected. The base64 encoded name field is receiving the correct updates, and the generation field under metadata is updating as expected.

If I refresh the site manually, the content is updated.

**What you expected to happen**:
When renaming a Scenario, the updated name should populate in the list of Scenarios as well as the available Scenarios in Courses.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Scenario and save it.
2. Update the name of the scenario.
3. Review the Scenario list to see if the name has updated.
4. Review the available Scenarios in Courses to see if the name has been updated.
5. Manually refresh the browser window.
6. Revisit steps 3 and 4 to see the name has updated.

**Anything else we need to know?**:
This may be related to an earlier submitted bug:
https://github.com/hobbyfarm/hobbyfarm/issues/364

**Environment**:
- Gargantua version: hobbyfarm/gargantua:v3.0.1-rc0
- UI/Admin version: hobbyfarm/admin-ui:v3.0.0, hobbyfarm/ui:v3.0.0
- Kubernetes version (use `kubectl version`): K3s v1.27.6+k3s1
- Cloud provider or hardware configuration:
```bash
6-core CPU
64GB RAM
50GB Disk
```
- OS (e.g: `cat /etc/os-release`):
```bash
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by jggoebel** [comment]
Should be resolved by https://github.com/hobbyfarm/admin-ui/pull/184. We can test this to verify

**Comment by eengelking** [comment]
What is the best way to test? Should I build the admin-ui image, or is there another image hosted somewhere that I can test with?

**Comment by jggoebel** [comment]
Had you tested this using a latest image build on master?

actually the pipeline should have pushed `hobbyfarm/admin-ui:master` which could be used to test this

**Comment by eengelking** [comment]
I'll test next week with the updates to the cluster.
