### ISSUE TITLE
Communication Platform

### ISSUE THREAD

**Issue by ebauman** [boxboat/hobbyfarm-chart#405]
We currently use the Rancher Users Slack as home for our project. 

It is currently not working, and has not been for several days. We need a new communication platform as this cannot continue. 

Should we get our own Slack instance? Or move to something like the Kubernetes slack?

**Comment by byteloop** [comment]
I am up for both options, maybe our own slack would be better

**Comment by ebauman** [comment]
https://twitter.com/Rancher_Labs/status/1745472334931386537

**Comment by ebauman** [comment]
If we do our own then yeah we can have nice integrations and things. I just worry about Slack instance sprawl! lol

**Comment by jggoebel** [comment]
Oh it might have been me reporting that crypto dude 😅. I wouldn’t think slack just blocks the whole rancher users slack  lol

**Comment by ebauman** [comment]
https://media4.giphy.com/media/3o751WPZAOqQBLx9aE/giphy.gif?cid=ecf05e47l518m3civ4z8b7jhdonugqs56arg5h4i1s8rnims&ep=v1_gifs_search&rid=giphy.gif&ct=g

**Comment by ebauman** [comment]
![image](https://media4.giphy.com/media/3o751WPZAOqQBLx9aE/giphy.gif?cid=ecf05e47l518m3civ4z8b7jhdonugqs56arg5h4i1s8rnims&ep=v1_gifs_search&rid=giphy.gif&ct=g)

**Comment by jggoebel** [comment]
So let’s just go with our own slack then?

**Comment by jggoebel** [comment]
Or do we want to stick to mailing lists 🤪

**Comment by ebauman** [comment]
You never got my original email so that won't work! LOL
I'll make a Slack for us.

**Comment by ebauman** [comment]
I built an open source Slack at www.buildingopensource.com 

Please join!

**Comment by jggoebel** [comment]
I updated the docs accordingly.

This issue can be closed then?

**Comment by ebauman** [comment]
Yes!
