### ISSUE TITLE
Basic docs are broken

### ISSUE THREAD

**Issue by bbaassssiiee** [boxboat/hobbyfarm-chart#421]
**What happened**:
I tried to read the docs

**What you expected to happen**:
Intro documentation

**How to reproduce it (as minimally and precisely as possible)**:
https://hobbyfarm.github.io/docs/setup/

**Anything else we need to know?**:
`Oops! This page doesn't exist. Try going back to the [home page](https://hobbyfarm.github.io/).`

**Environment**:
- Github.com

**Comment by jggoebel** [comment]
Hey! Thanks for the notice 
Where did you get the link to this page /setup? 
Was it linked somewhere?

**Comment by bbaassssiiee** [comment]
https://hobbyfarm.github.io/hobbyfarm/

More advanced setup infos can be found [here](https://hobbyfarm.github.io/docs/setup/)

**Comment by jggoebel** [comment]
Removed the link. This was from an old version of the docs and therefore could be removed
