### ISSUE TITLE
Docs lag release

### ISSUE THREAD

**Issue by bbaassssiiee** [boxboat/hobbyfarm-chart#422]
**What happened**:
I looked at https://hobbyfarm.github.io/ and noticed its release version is outdated.

**What you expected to happen**:
Up2date starter docs on an exiting project.

**How to reproduce it (as minimally and precisely as possible)**:
https://hobbyfarm.github.io/

**Anything else we need to know?**:
Delight the new-comers!

**Environment**:
- Github

**Comment by jggoebel** [comment]
I added the current versoin 3.1.0 to the list. Thank you for noticing.

Next time please create doc related issues directly in the docs repo https://github.com/hobbyfarm/hobbyfarm.github.io as we track documentation issues there.
