### ISSUE TITLE
Allow click to file when CTR is disabled

### ISSUE THREAD

**Issue by ebartz** [boxboat/hobbyfarm-chart#424]
**What happened**:

A user disabled the CTR Feature in the settings. And Clicked on a click to file element. But when CTR is disabled, you can also not use CTF elements.

**What you expected to happen**:
Click to run is disabked while click to file still works.

**How to reproduce it (as minimally and precisely as possible)**:
Start a scenario that uses click to file with a user that has the CTR Feature disabled.

**Comment by jggoebel** [comment]
We could add a "Disable CTF" flag.
I could imagine that a user does not want to type a whole file himself, and he could leave CTF enabled and only disable CTR like it is right now.
