### ISSUE TITLE
Manual creation of accounts given admin role are unable to login to the admin-ui

### ISSUE THREAD

**Issue by testmad** [boxboat/hobbyfarm-chart#445]
**What happened**:
Since the admin account in the values.yaml is broken, I tried manual creation via the following yaml:
```
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
  name: admin
  namespace: hobbyfarm-system
spec:
  email: admin
  password: $2a$10$z6T6lVwLofkXfVS0DfHp9uSYELATARuUIDXalSmGR.DcNYgZrkxWG
  access_codes: []
  settings:
    terminal_theme: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: hobbyfarm-admin-rolebinding
    namespace: hobbyfarm-system
subjects:
- kind: User
  name: admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: hobbyfarm-admin
  apiGroup: rbac.authorization.k8s.io
  ```
  Applying this yaml does create a user named admin and does give it the admin role. You can login to the learn-ui with this user. Attempting to login to the admin-ui with this user results in nothing. Not even an incorrect login or server error being displayed. Checking the browser developer tools shows `500` on the api service.

**What you expected to happen**:
Successful login to the admin ui

**How to reproduce it (as minimally and precisely as possible)**:
Apply the supplied yaml and try to login to the admin-ui

**Anything else we need to know?**:
It seems that if i register a user via the learn ui and then apply the role I can login to the admin-ui.

Here is a log from the authn service when trying to use the yaml created user:
```
I0711 18:10:11.288958       1 microservices.go:191] Resolved connection to user-service (State READY)
2024-07-11T14:10:12.621402603-04:00 I0711 18:10:12.621197       1 microservices.go:200] Connection to rbac-service is now in state IDLE
2024-07-11T14:10:12.621522134-04:00 I0711 18:10:12.621422       1 microservices.go:200] Connection to rbac-service is now in state CONNECTING
2024-07-11T14:10:12.625112024-04:00 I0711 18:10:12.624956       1 microservices.go:191] Resolved connection to rbac-service (State READY)
2024-07-11T14:14:27.619820120-04:00 E0711 18:14:27.619451       1 authnservice.go:557] rpc error: code = Unknown desc = not found
```

Affects 3.2.1+

**Environment**:
- Gargantua version:
- UI/Admin version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

**Comment by jggoebel** [comment]
Thank you for providing this issue. We will look into this

**Comment by jggoebel** [comment]
Ah i think this is due to https://github.com/svalabs/hobbyfarm/blob/3584d68c2b681161518d2ebf12c470c8a7a240ce/charts/hobbyfarm/templates/rbac-service/role.yaml

also a file in the wrong namespace.

**Comment by jggoebel** [comment]
Can you verify for me if the Role `hobbyfarm-admin` exists in the correct namespace?

**Comment by testmad** [comment]
Had to add the admin role to the right namespace manually but after that i was able to login with the created user.
