### ISSUE TITLE
"Hide Usernames" on Dashboard should be saved in the users settings

### ISSUE THREAD

**Issue by jggoebel** [boxboat/hobbyfarm-chart#457]
**What would you like to be added**:
Trainers can enable "hide usernames" to share the screen to the group taking the training without leaking names.

**Why is this needed**:
This switch is not persisted and upon reload of the page the switch is back to the default which shows the usernames

**Comment by tanemlu** [comment]
Das Ticket übernehme ich :)

**Comment by jggoebel** [comment]
Closed by https://github.com/hobbyfarm/admin-ui/pull/226
